@startuml
!theme reddress-lightred
scale max 600 height
title Choosing Game Modes From the Starting Menu
'define swimlanes
|#technology|Player|
|#implementation|System|
|System|
start
:Presents start menu;
|Player|
:Select the number of gameshows they'd like to play;
while(Has number of game shows been chosen?) is (no)
:Prints out a selection of game shows to choose from;
while(Game show  been selected?) is (no)
:Selects a game show to play;
|System|
if(Has a valid selection been made?) then (yes)

:Add to list of game shows;
endif
end while
endwhile

:Begin the game;
stop

@enduml
