@startuml
(start) #green
:System:
:Player:
(start) -> Player
Player --> (Opens app)
(Chooses game mode) <-- (Opens app)
package Mode {
    usecase "Activates single-player" as SPM
    usecase "Activates multiplayer" as MPM
    }
usecase "Registers game mode" as reg
System -- reg
(Chooses game mode) -> reg
reg --> SPM
reg --> MPM
package QuestionPhase{
usecase "Provides question to Player" as PQ
usecase "Answers question" as AQ
PQ --> AQ

usecase "Reveals answer" as RRC
AQ --> RRC
System -- RRC
}

:Question Database: as QD
SPM --> QuestionPhase
MPM --> QuestionPhase
System -- PQ
QD -- PQ


package BreakOut {
usecase "Gives incorrect response" as IR
usecase "Answers all 10 questions correctly" as AR
}
QuestionPhase ----> BreakOut
usecase "Prints player's game results" as PGR
usecase "END" #red
BreakOut -> PGR
PGR -> END
@enduml